import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { MessageSquare, ChevronRight } from "lucide-react";
import { useChatSession } from "@components/react"; // Corrected import path for useChatSession

export default function FollowUpSuggestions(props) { // Pass props to the component function
  const [selectedIndex, setSelectedIndex] = useState(null);
  const { sendMessage } = useChatSession(); // Get sendMessage from useChatSession
  
  // Suggestions should now always come from props, generated by the LLM
  const suggestions = props.suggestions;
  
  // Don't render if there are no suggestions
  if (!suggestions || suggestions.length === 0) {
    return null;
  }
  
  const handleSuggestionClick = (suggestion, index) => {
    setSelectedIndex(index);
    // Send the suggestion as a user message using Chainlit's sendMessage
    sendMessage(suggestion);
  };
  
  return (
    <Card className="w-full max-w-md border-2 border-primary/10">
      <CardHeader className="pb-2">
        <CardTitle className="text-md font-medium flex items-center gap-2">
          <MessageSquare className="h-4 w-4" />
          {props.title || "Follow-up Suggestions"}
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="flex flex-col gap-2">
          {suggestions.map((suggestion, index) => (
            <Button
              key={index}
              variant={selectedIndex === index ? "default" : "outline"}
              className="justify-between text-left font-normal hover:bg-primary/10 transition-all"
              onClick={() => handleSuggestionClick(suggestion, index)}
              disabled={selectedIndex !== null} // Disable all buttons once one is clicked
            >
              <span>{suggestion}</span>
              <ChevronRight className="h-4 w-4 ml-2 opacity-70" />
            </Button>
          ))}
        </div>
      </CardContent>
    </Card>
  );
}
